package com.near.clients.jdbi;

import java.util.ArrayList;
import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;
import com.near.clients.api.Client;
import com.near.clients.mappers.ClientMapper;

/**
 * This interface is used by JDBI to query information about AppUsers. 
 * 
 * @author rbadillo
 *
 */
@RegisterMapper(ClientMapper.class)
public interface ClientDAO {
  /** Inserts a Client to the DB. The ID is auto generated by the DB when stored.*/
  @SqlUpdate("INSERT INTO Clients (name) VALUES (:name)")
  void insert(@Bind("name") String name);
  
  /**  Queries all the clients from the DB */
  @SqlQuery("SELECT id, name FROM Clients")
  ArrayList<Client> getAllClients();
  
  /**  Queries a single Client with the ID from the DB */
  @SqlQuery("SELECT id, name FROM Clients WHERE id = :id")
  Client findClientById(@Bind("id") long id);

  /** Close with no args is used to close the connection by DropWizard */  
  void close();
}
