package com.near.appusers.jdbi;

import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;

import com.near.appusers.api.AppUser;

/**
 * This interface is used by JDBI to query information about AppUsers. 
 * 
 * @author zwkero
 *
 */
@RegisterMapper(AppUser.Mapper.class)
public interface AppUserDAO {
  /** Inserts a AppUser to the DB. The ID is auto generated by the DB when stored.*/
  @SqlUpdate("INSERT INTO AppUsers (name, age) VALUES (:name, :age)")
  void insert(@Bind("name") String name, @Bind("age") int age);
  
  /**  Queries all the people from the DB */
  @SqlQuery("SELECT id, name, age FROM AppUsers")
  String getAllPeople(@Bind("id") int id);
  
  /**  Queries a single AppUser with the ID from the DB */
  @SqlQuery("SELECT id, name, age FROM AppUsers WHERE id = :id")
  String findAppUserById(@Bind("id") int id);

  /** Close with no args is used to close the connection by DropWizard */  
  void close();
}
